#include "gpu/Compositor.h"

#include "util/HResult.h"

#include <algorithm>
#include <cmath>

// Generated by fxc at build time (see cmake/LumaShaders.cmake).
#include "g_VSMain.h"
#include "g_PS_Composite.h"
#include "g_PS_Preview.h"
#include "g_PS_UV.h"
#include "g_PS_Y.h"

namespace luma::gpu {
namespace {

// Must mirror cbuffer Params in Compose.hlsl (21 float4 registers).
struct alignas(16) Params {
    float outSize[2], srcSize[2];
    float srcCrop[4];
    float destRect[4];
    float cursorPos[2], cursorSize[2];
    float mousePos[2], hlRadius, hlEnabled;
    float hlColor[4];
    float clicks[4][4];
    float clickColorL[4];
    float clickColorR[4];
    float clickRadius, fxEnabled, brightness, contrast;
    float saturation, invGamma, temperature, tint;
    float sharpen, blurRadius, grayscale, srcScale;
    float camRect[4];
    float camUv[4];
    float camBorderColor[4];
    float camEnabled, camShape, camRadius, camBorder;
    float camOpacity, overlayEnabled, pad0[2];
    float overlayBounds[4];
};
static_assert(sizeof(Params) == 21 * 16);

void setColor(float (&dst)[4], const Rgba& c)
{
    dst[0] = c.r;
    dst[1] = c.g;
    dst[2] = c.b;
    dst[3] = c.a;
}

void makeTarget(ID3D11Device* device, unsigned w, unsigned h, DXGI_FORMAT fmt, ComPtr<ID3D11Texture2D>& tex,
                ComPtr<ID3D11RenderTargetView>& rtv, const char* what, ComPtr<ID3D11ShaderResourceView>* srv = nullptr)
{
    D3D11_TEXTURE2D_DESC desc{};
    desc.Width = w;
    desc.Height = h;
    desc.MipLevels = 1;
    desc.ArraySize = 1;
    desc.Format = fmt;
    desc.SampleDesc.Count = 1;
    desc.Usage = D3D11_USAGE_DEFAULT;
    desc.BindFlags = D3D11_BIND_RENDER_TARGET | (srv ? D3D11_BIND_SHADER_RESOURCE : 0u);
    check(device->CreateTexture2D(&desc, nullptr, &tex), what);
    check(device->CreateRenderTargetView(tex.Get(), nullptr, &rtv), what);
    if (srv)
        check(device->CreateShaderResourceView(tex.Get(), nullptr, srv->ReleaseAndGetAddressOf()), what);
}

// Must mirror cbuffer PreviewParams in Compose.hlsl.
struct alignas(16) PreviewParams {
    float previewSize[2], pad[2];
};
static_assert(sizeof(PreviewParams) == 16);

void makeShaderTexture(ID3D11Device* device, unsigned w, unsigned h, ComPtr<ID3D11Texture2D>& tex,
                       ComPtr<ID3D11ShaderResourceView>& srv, const char* what)
{
    D3D11_TEXTURE2D_DESC desc{};
    desc.Width = w;
    desc.Height = h;
    desc.MipLevels = 1;
    desc.ArraySize = 1;
    desc.Format = DXGI_FORMAT_B8G8R8A8_UNORM;
    desc.SampleDesc.Count = 1;
    desc.Usage = D3D11_USAGE_DEFAULT;
    desc.BindFlags = D3D11_BIND_SHADER_RESOURCE;
    srv.Reset();
    tex.Reset();
    check(device->CreateTexture2D(&desc, nullptr, &tex), what);
    check(device->CreateShaderResourceView(tex.Get(), nullptr, &srv), what);
}

} // namespace

Compositor::Compositor(ID3D11Device* device, unsigned outW, unsigned outH, bool bgraOutput)
    : m_device(device), m_outW(outW), m_outH(outH), m_bgra(bgraOutput)
{
    check(device->CreateVertexShader(g_VSMain, sizeof(g_VSMain), nullptr, &m_vs), "CreateVertexShader");
    check(device->CreatePixelShader(g_PS_Y, sizeof(g_PS_Y), nullptr, &m_psY), "CreatePixelShader(Y)");
    check(device->CreatePixelShader(g_PS_UV, sizeof(g_PS_UV), nullptr, &m_psUV), "CreatePixelShader(UV)");
    check(device->CreatePixelShader(g_PS_Composite, sizeof(g_PS_Composite), nullptr, &m_psComposite),
          "CreatePixelShader(Composite)");

    D3D11_SAMPLER_DESC sd{};
    sd.Filter = D3D11_FILTER_MIN_MAG_MIP_LINEAR;
    sd.AddressU = sd.AddressV = sd.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
    sd.MaxLOD = D3D11_FLOAT32_MAX;
    check(device->CreateSamplerState(&sd, &m_sampler), "CreateSamplerState");

    D3D11_BUFFER_DESC bd{};
    bd.ByteWidth = sizeof(Params);
    bd.Usage = D3D11_USAGE_DEFAULT;
    bd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
    check(device->CreateBuffer(&bd, nullptr, &m_params), "CreateBuffer(params)");

    if (bgraOutput) {
        makeTarget(device, outW, outH, DXGI_FORMAT_B8G8R8A8_UNORM, m_bgraTex, m_bgraRtv, "BGRA target");
    } else {
        makeTarget(device, outW, outH, DXGI_FORMAT_R8_UNORM, m_yTex, m_yRtv, "Y target", &m_ySrv);
        makeTarget(device, outW / 2, outH / 2, DXGI_FORMAT_R8G8_UNORM, m_uvTex, m_uvRtv, "UV target", &m_uvSrv);
        check(device->CreatePixelShader(g_PS_Preview, sizeof(g_PS_Preview), nullptr, &m_psPreview),
              "CreatePixelShader(Preview)");
        D3D11_BUFFER_DESC pd{};
        pd.ByteWidth = sizeof(PreviewParams);
        pd.Usage = D3D11_USAGE_DEFAULT;
        pd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
        check(device->CreateBuffer(&pd, nullptr, &m_previewParams), "CreateBuffer(preview params)");
    }
}

bool Compositor::ensurePreview(unsigned width, unsigned height)
{
    if (m_bgra || width < 16 || height < 16)
        return false;
    if (m_previewTex && width == m_previewW && height == m_previewH)
        return true;
    m_previewRtv.Reset();
    m_previewTex.Reset();
    makeTarget(m_device, width, height, DXGI_FORMAT_B8G8R8A8_UNORM, m_previewTex, m_previewRtv, "preview target");
    m_previewW = width;
    m_previewH = height;
    return true;
}

void Compositor::renderPreview(ID3D11DeviceContext* ctx)
{
    if (m_bgra || !m_previewRtv)
        return;
    PreviewParams pp{};
    pp.previewSize[0] = static_cast<float>(m_previewW);
    pp.previewSize[1] = static_cast<float>(m_previewH);
    ctx->UpdateSubresource(m_previewParams.Get(), 0, nullptr, &pp, 0, 0);

    ID3D11ShaderResourceView* srvs[2] = {m_ySrv.Get(), m_uvSrv.Get()};
    ID3D11Buffer* cb = m_previewParams.Get();
    ID3D11SamplerState* sampler = m_sampler.Get();
    ctx->IASetInputLayout(nullptr);
    ctx->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
    ctx->VSSetShader(m_vs.Get(), nullptr, 0);
    ctx->PSSetShaderResources(5, 2, srvs);
    ctx->PSSetSamplers(0, 1, &sampler);
    ctx->PSSetConstantBuffers(1, 1, &cb);
    draw(ctx, m_psPreview.Get(), m_previewRtv.Get(), m_previewW, m_previewH);

    ID3D11ShaderResourceView* nullSrvs[2] = {};
    ctx->PSSetShaderResources(5, 2, nullSrvs);
    ctx->OMSetRenderTargets(0, nullptr, nullptr);
}

void Compositor::setSettings(ID3D11DeviceContext* ctx, const CompositionSettings& settings)
{
    m_settings = settings;
    if (settings.overlay == m_uploadedOverlay)
        return;
    m_uploadedOverlay = settings.overlay;
    m_overlayValid = false;
    const OverlayImage* img = settings.overlay.get();
    if (!img || img->width != m_outW || img->height != m_outH || img->pixels.size() < size_t(m_outW) * m_outH ||
        img->boundsW <= 0 || img->boundsH <= 0)
        return; // wrong size or empty: overlay layer disabled
    if (!m_overlayTex)
        makeShaderTexture(m_device, m_outW, m_outH, m_overlayTex, m_overlaySrv, "overlay texture");
    ctx->UpdateSubresource(m_overlayTex.Get(), 0, nullptr, img->pixels.data(), m_outW * 4, 0);
    m_overlayValid = true;
}

void Compositor::setWebcamFrame(ID3D11DeviceContext* ctx, const uint32_t* pixels, unsigned w, unsigned h)
{
    if (!pixels || w == 0 || h == 0)
        return;
    if (!m_camTex || w != m_camW || h != m_camH) {
        makeShaderTexture(m_device, w, h, m_camTex, m_camSrv, "webcam texture");
        m_camW = w;
        m_camH = h;
    }
    ctx->UpdateSubresource(m_camTex.Get(), 0, nullptr, pixels, w * 4, 0);
    m_camValid = true;
}

void Compositor::draw(ID3D11DeviceContext* ctx, ID3D11PixelShader* ps, ID3D11RenderTargetView* rtv, unsigned w, unsigned h)
{
    const D3D11_VIEWPORT vp{0, 0, static_cast<float>(w), static_cast<float>(h), 0, 1};
    ctx->RSSetViewports(1, &vp);
    ctx->OMSetRenderTargets(1, &rtv, nullptr);
    ctx->PSSetShader(ps, nullptr, 0);
    ctx->Draw(3, 0);
}

void Compositor::render(ID3D11DeviceContext* ctx, const FrameInputs& in)
{
    Params p{};
    const float ow = static_cast<float>(m_outW), oh = static_cast<float>(m_outH);
    p.outSize[0] = ow;
    p.outSize[1] = oh;
    p.srcSize[0] = static_cast<float>(std::max(1u, in.srcWidth));
    p.srcSize[1] = static_cast<float>(std::max(1u, in.srcHeight));

    // Crop (clamped to the source) and letterboxed destination rectangle.
    float cx = 0, cy = 0, cw = p.srcSize[0], ch = p.srcSize[1];
    if (in.crop.right > in.crop.left && in.crop.bottom > in.crop.top) {
        cx = std::clamp(static_cast<float>(in.crop.left), 0.f, p.srcSize[0] - 1);
        cy = std::clamp(static_cast<float>(in.crop.top), 0.f, p.srcSize[1] - 1);
        cw = std::clamp(static_cast<float>(in.crop.right - in.crop.left), 1.f, p.srcSize[0] - cx);
        ch = std::clamp(static_cast<float>(in.crop.bottom - in.crop.top), 1.f, p.srcSize[1] - cy);
    }
    const float scale = std::min(ow / cw, oh / ch);
    const float dw = cw * scale, dh = ch * scale;
    p.srcCrop[0] = cx;
    p.srcCrop[1] = cy;
    p.srcCrop[2] = cw;
    p.srcCrop[3] = ch;
    p.destRect[0] = std::floor((ow - dw) * 0.5f);
    p.destRect[1] = std::floor((oh - dh) * 0.5f);
    p.destRect[2] = dw;
    p.destRect[3] = dh;
    p.srcScale = 1.0f / scale;

    if (in.cursor && in.cursorPlacement.visible && in.cursor->width() > 0) {
        p.cursorPos[0] = static_cast<float>(in.cursorPlacement.x);
        p.cursorPos[1] = static_cast<float>(in.cursorPlacement.y);
        p.cursorSize[0] = static_cast<float>(in.cursor->width());
        p.cursorSize[1] = static_cast<float>(in.cursor->height());
    }

    const CursorEffects& ce = m_settings.cursor;
    p.mousePos[0] = in.mouseX;
    p.mousePos[1] = in.mouseY;
    p.hlEnabled = (ce.highlight && in.mouseValid) ? 1.f : 0.f;
    p.hlRadius = ce.highlightRadius;
    setColor(p.hlColor, ce.highlightColor);
    for (size_t i = 0; i < in.clicks.size(); ++i) {
        const ClickRing& k = in.clicks[i];
        p.clicks[i][0] = k.x;
        p.clicks[i][1] = k.y;
        p.clicks[i][2] = k.progress;
        p.clicks[i][3] = ce.clicks ? static_cast<float>(k.button) : 0.f;
    }
    setColor(p.clickColorL, ce.leftClickColor);
    setColor(p.clickColorR, ce.rightClickColor);
    p.clickRadius = ce.clickRadius;

    const VideoFilterSettings& f = m_settings.filters;
    p.fxEnabled = f.enabled ? 1.f : 0.f;
    p.brightness = f.brightness;
    p.contrast = f.contrast;
    p.saturation = f.saturation;
    p.invGamma = 1.0f / std::clamp(f.gamma, 0.2f, 5.0f);
    p.temperature = f.temperature;
    p.tint = f.tint;
    p.sharpen = f.enabled ? f.sharpen : 0.f;
    p.blurRadius = f.enabled ? f.blur : 0.f;
    p.grayscale = f.grayscale ? 1.f : 0.f;

    const WebcamPlacement& cam = m_settings.webcam;
    if (cam.enabled && m_camValid) {
        p.camEnabled = 1;
        p.camRect[0] = cam.x * ow;
        p.camRect[1] = cam.y * oh;
        p.camRect[2] = std::max(8.f, cam.w * ow);
        p.camRect[3] = std::max(8.f, cam.h * oh);
        float u0 = std::clamp(cam.cropLeft, 0.f, 0.45f), u1 = 1.f - std::clamp(cam.cropRight, 0.f, 0.45f);
        const float v0 = std::clamp(cam.cropTop, 0.f, 0.45f), v1 = 1.f - std::clamp(cam.cropBottom, 0.f, 0.45f);
        if (cam.mirror)
            std::swap(u0, u1);
        p.camUv[0] = u0;
        p.camUv[1] = v0;
        p.camUv[2] = u1;
        p.camUv[3] = v1;
        p.camShape = static_cast<float>(static_cast<int>(cam.shape));
        p.camRadius = cam.cornerRadius * std::min(p.camRect[2], p.camRect[3]);
        p.camBorder = std::max(0.f, cam.borderPx);
        setColor(p.camBorderColor, cam.borderColor);
        p.camOpacity = std::clamp(cam.opacity, 0.f, 1.f);
    }

    if (m_overlayValid && m_uploadedOverlay) {
        const OverlayImage& o = *m_uploadedOverlay;
        p.overlayEnabled = 1;
        p.overlayBounds[0] = static_cast<float>(o.boundsX) - 1;
        p.overlayBounds[1] = static_cast<float>(o.boundsY) - 1;
        p.overlayBounds[2] = static_cast<float>(o.boundsX + o.boundsW) + 1;
        p.overlayBounds[3] = static_cast<float>(o.boundsY + o.boundsH) + 1;
    }

    ctx->UpdateSubresource(m_params.Get(), 0, nullptr, &p, 0, 0);

    ID3D11ShaderResourceView* srvs[5] = {
        in.source,
        in.cursor ? in.cursor->colorSrv() : nullptr,
        in.cursor ? in.cursor->invertSrv() : nullptr,
        m_camValid ? m_camSrv.Get() : nullptr,
        m_overlayValid ? m_overlaySrv.Get() : nullptr,
    };
    ID3D11Buffer* cb = m_params.Get();
    ID3D11SamplerState* sampler = m_sampler.Get();
    ctx->IASetInputLayout(nullptr);
    ctx->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
    ctx->VSSetShader(m_vs.Get(), nullptr, 0);
    ctx->PSSetShaderResources(0, 5, srvs);
    ctx->PSSetSamplers(0, 1, &sampler);
    ctx->PSSetConstantBuffers(0, 1, &cb);

    if (m_bgra) {
        draw(ctx, m_psComposite.Get(), m_bgraRtv.Get(), m_outW, m_outH);
    } else {
        draw(ctx, m_psY.Get(), m_yRtv.Get(), m_outW, m_outH);
        draw(ctx, m_psUV.Get(), m_uvRtv.Get(), m_outW / 2, m_outH / 2);
    }

    // Unbind so source textures can be written by the next CopyResource without hazards.
    ID3D11ShaderResourceView* nullSrvs[5] = {};
    ctx->PSSetShaderResources(0, 5, nullSrvs);
    ctx->OMSetRenderTargets(0, nullptr, nullptr);
}

} // namespace luma::gpu
